# Generated by Django 6.0.2 on 2026-02-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_historicalproduct_historicalproductrawmaterial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductrawmaterial',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalrawmaterial',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productrawmaterial',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
