# Generated by Django 6.0.2 on 2026-02-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_historicalproductrawmaterial_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='stock',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productionlog',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionlog',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
