# Generated by Django 6.0.2 on 2026-02-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_historicalproduct_stock_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalrawmaterial',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='raw_materials/'),
        ),
    ]
