# Generated by Django 6.0.2 on 2026-02-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_historicalproduct_image_historicalrawmaterial_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductrawmaterial',
            name='manufacturing_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productrawmaterial',
            name='manufacturing_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
